name: Bazel Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { CC: clang, os: ubuntu-20.04, flags: "" }
          - { CC: clang, os: ubuntu-20.04, flags: "-c opt" }  # Some warnings only fire with -c opt
          - { CC: gcc, os: ubuntu-20.04, flags: "-c opt" }
          - { CC: clang, os: ubuntu-20.04, flags: "--//:fasttable_enabled=true -- -cmake:test_generated_files" }
          - { CC: clang, os: ubuntu-20.04, flags: "--config=asan -- -benchmarks:benchmark -python:all" }
          - { CC: clang, os: macos-11, flags: "" }

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cd ${{ github.workspace }} && CC=${{ matrix.CC }} bazel test ... ${{ matrix.flags }}
