name: Bazel Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { flags: "" }
          - { flags: "--//:fasttable_enabled=true -- -cmake:test_generated_files" }
          - { flags: "--config=asan -- -benchmarks:benchmark" }

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cd ${{ github.workspace }} && bazel test ... ${{ matrix.flags }}
