name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { CC: gcc, CXX: g++ }
          - { CC: clang, CXX: clang++ }

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info
      - uses: actions/checkout@v2
        with:
          path: upb
      - name: Run tests
        run: ${{ github.workspace }}/kokoro/ubuntu/build.sh
