name: PHP extension

on:
  - push
  - pull_request

jobs:
  build-php:
    name: Build PHP extension
    runs-on: ubuntu-latest
    container: ${{ matrix.php-image }}
    strategy:
      matrix:
        php-image:
          - php:7.4-cli
          - php:8.1-cli
    steps:
      - name: Install bazel
        run: |
          apt-get update -q
          apt-get install -qy bazel
      - name: Install git
        run: |
          apt-get install -qy --no-install-recommends git
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create package
        run: |
          rm -rf bazel-bin/php/protobuf-*.tgz
          cd $GITHUB_WORKSPACE
          bazel build php:release
      - name: Compile extension
        run: |
          cd /tmp
          MAKE="make -j$(nproc)" pecl install bazel-bin/php/protobuf-*.tgz
      - name: Enable extension
        run: docker-php-ext-enable protobuf
      - name: Inspect extension
        run: php --ri protobuf
